server:
  port: 8090
  
spring:
  application:
    name: geocode-service 
    
eureka:
  client:
    register-with-eureka: true 
    service-url:
      defaultZone: http://localhost:8761/eureka/